from fastapi import APIRouter

from crm.api.v1.endpoints import (
    activity,
    alerts,
    analytics,
    assignment_rules,
    auth,
    call_summary,
    campaigns,
    cron,
    inventory,
    settings,
    leads,
    lead_intake,
    marketing,
    meta_capi,
    meta_leads_webhook,
    misc,
    my_dashboard,
    notifications,
    platform_ops,
    projects,
    reminders,
    suggestions,
    tasks,
    transfers,
    users,
    whatsapp,
    webflow_leads_webhook,
)

api_router = APIRouter()

for r in [
    auth.router,
    projects.router,
    inventory.router,
    leads.router,
    lead_intake.router,
    analytics.router,
    campaigns.router,
    call_summary.router,
    tasks.router,
    notifications.router,
    assignment_rules.router,
    alerts.router,
    suggestions.router,
    whatsapp.router,
    activity.router,
    my_dashboard.router,
    platform_ops.router,
    transfers.router,
    users.router,
    marketing.router,
    reminders.router,
    cron.router,
    settings.router,
    meta_capi.router,
    meta_leads_webhook.router,
    webflow_leads_webhook.router,
    misc.router,
]:
    api_router.include_router(r)
